### ISSUE TITLE
Navigation not centered.

### ISSUE THREAD

**Issue by trev-dev** [Coltcedar9219/Cat-Site#3]
## Heyo

It looks like the navigation is not centered. There's some default padding that's pushing it over to the right a little bit.

![Screenshot_2019-05-10_09-58-33](https://user-images.githubusercontent.com/28788713/57543707-fe4efc80-7309-11e9-8b52-c6d0c0e2ad71.png)

I have submitted a pull request to fix this issue here: https://github.com/Coltcedar9219/Cat-Site/pull/2

**Comment by Coltcedar9219** [comment]
Ive merged it. thank you!
